### ISSUE TITLE
Resume Upload API

### ISSUE THREAD

**Issue by guilleeh** [SHPE-at-UCI/clubs.uci.edu.shpe#53]
As a user, when I drag and drop a resume file on the dashboard page, it should be uploaded to a Google Drive Folder.

**TO-DO**
- [x] Follow this easy 30-min Google Drive API Codelab: https://codelabs.developers.google.com/codelabs/gsuite-apis-intro/#0
- [x] Get familiar with our Python Flask repository. Go through this tutorial: https://flask.palletsprojects.com/en/1.1.x/tutorial/
- [x] Create a branch `resume-upload-api`, & publish it to github servers
- [x] Look around the `Sumbit` button in _templates/dashboard.html_, 
- [x] Create a `dashboard.py` in `/routes` (similar to `settings.py`) to handle the POST request triggered from submit button
- [x] Import `dashboard` from `routes` and register `app.register_blueprint(dashboard.bp)` in `__init__.py`
- [x] Write logic for Drive Upload:   
1. Extract file from `request.form`
2. Setup Drive API Simple upload ( uploadType=media )
3. Send the file using API
4. Delete file from local repo
- [x] Test getting Drive API key,  try to save a file into a nested folder
- [x] Find user name metadata stored in the `app` variable in flask, and use it to upload `Lastname_Firstname.pdf`
 Look at setting.py db.child
- [x] If the user uploads a resume again, (write over the old resume file on GDrive OR deletes the file and reupload new)

Solution to Blocker:
- [x] edit `auth.py` in `@bp.route('/register',` to add a `resume_id: None` in the `data` 
- [ ] Coordinate zoom call with Josue to wipe out Firebase, Merge Redeploy
- [ ] Test creating a new account, 
- [x] Add if conditional in `dashboard.py` for `POST` handler if `resume_id` is not empty then update file

End Goal:
- [x] GET request for /dashboard loads a usual, but POST request for /dashboard is reserve to upload resumes

UI/UX
- [x]  Add a flask conditional statement: "if data variable exist; then: show message; else "Drag Resume here" " 
- [ ] `return render_template()` that sends `data` dictionary with a message "Resume Uploaded"

Extra

- [ ] Try using `resumable upload` with Drive API

**Comment by guilleeh** [comment]
Any progress on this?

**Comment by JuiceBox1992** [comment]
Hey Memo so far no. Ive been stuck on it-HugoSent from my Metro By T-Mobile 4G LTE Android Device
-------- Original message --------From: Guillermo Hernandez <notifications@github.com> Date: 4/22/20  1:21 PM  (GMT-08:00) To: "SHPE-at-UCI/clubs.uci.edu.shpe" <clubs.uci.edu.shpe@noreply.github.com> Cc: JuiceBox1992 <hacevesi@uci.edu>, Assign <assign@noreply.github.com> Subject: Re: [SHPE-at-UCI/clubs.uci.edu.shpe] Brainstorm User Upload Resume (#53) 
Any progress on this?

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SHPE-at-UCI/clubs.uci.edu.shpe/issues/53#issuecomment-618017972",
"url": "https://github.com/SHPE-at-UCI/clubs.uci.edu.shpe/issues/53#issuecomment-618017972",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by guilleeh** [comment]
No worries. If you can, let us know if you need help or if you would like to give the issue to someone with more bandwidth. :)

**Comment by JuiceBox1992** [comment]
i think if i dont get close too finishing it by this friday i would wanna tag along with someone to do it together.Sent from my Metro By T-Mobile 4G LTE Android Device
-------- Original message --------From: Guillermo Hernandez <notifications@github.com> Date: 4/22/20  7:45 PM  (GMT-08:00) To: "SHPE-at-UCI/clubs.uci.edu.shpe" <clubs.uci.edu.shpe@noreply.github.com> Cc: JuiceBox1992 <hacevesi@uci.edu>, Assign <assign@noreply.github.com> Subject: Re: [SHPE-at-UCI/clubs.uci.edu.shpe] Brainstorm User Upload Resume (#53) 
No worries. If you can, let us know if you need help or if you would like to give the issue to someone with more bandwidth. :)

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SHPE-at-UCI/clubs.uci.edu.shpe/issues/53#issuecomment-618144164",
"url": "https://github.com/SHPE-at-UCI/clubs.uci.edu.shpe/issues/53#issuecomment-618144164",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by josueal1** [comment]
@guilleeh Co-assigning this task to @Johan-Cuevas as his bandwidth has been available and MemberSHPE Chair is requesting this resume drop feature to be produced ASAP. @JuiceBox1992 @bcid You both are welcomed to coordinate & meet with @Johan-Cuevas as your times permits :)

**Comment by josueal1** [comment]
@Johan-Cuevas Updating task deliverable:  _it should be uploaded to a Google Drive Folder_   Python DriveAPI Codelab Walkthrough: https://codelabs.developers.google.com/codelabs/gsuite-apis-intro/#0

**Comment by josueal1** [comment]
Added Blocker:  must save `resume_id` if first time uploading,  save `null` when first creating an account, get `user_data` before updating data in `settings.py` @Johan-Cuevas
