### ISSUE TITLE
Resume Upload UX

### ISSUE THREAD

**Issue by josueal1** [SHPE-at-UCI/clubs.uci.edu.shpe#94]
As a user, when I drag and drop a resume file on the dashboard page, the app should tell me if I'm uploading a file incorrectly 

**TODO**
- [ ] Familiarize with the `<input type="file">` html tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
- [ ] Verify filename as **_Lastname_Firstname_resume.pdf_** using regex: https://stackoverflow.com/questions/25801247/regular-expression-to-find-lastname-firstname-middlename-format
- [ ] Ensure `MIMEtype`of file is a `application/pdf`. Here's basic html & js file checker->: https://gist.github.com/topalex/ad13f76150e0b36de3c4a3d5ba8dc63a
